//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteToolSuite.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiteToolSuite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT消息 的本地化字符串。
        /// </summary>
        internal static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆查看 的本地化字符串。
        /// </summary>
        internal static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件改名 的本地化字符串。
        /// </summary>
        internal static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间/时间戳 的本地化字符串。
        /// </summary>
        internal static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string Feature5 {
            get {
                return ResourceManager.GetString("Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录后端站点 的本地化字符串。
        /// </summary>
        internal static string Feature6 {
            get {
                return ResourceManager.GetString("Feature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出测试内容生成 的本地化字符串。
        /// </summary>
        internal static string Feature7 {
            get {
                return ResourceManager.GetString("Feature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Feature8 {
            get {
                return ResourceManager.GetString("Feature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出程序 的本地化字符串。
        /// </summary>
        internal static string Feature9 {
            get {
                return ResourceManager.GetString("Feature9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string MessageBoxCapInformation {
            get {
                return ResourceManager.GetString("MessageBoxCapInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入11位手机号码 的本地化字符串。
        /// </summary>
        internal static string PhoneNumberPrompt {
            get {
                return ResourceManager.GetString("PhoneNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个是简体中文！ 的本地化字符串。
        /// </summary>
        internal static string PopMessage {
            get {
                return ResourceManager.GetString("PopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入搜索内容 的本地化字符串。
        /// </summary>
        internal static string SearchTextPrompt {
            get {
                return ResourceManager.GetString("SearchTextPrompt", resourceCulture);
            }
        }
    }
}
